### ISSUE TITLE
Missing decoder: H.264

### ISSUE THREAD

**Issue by ho0-kim** [dluvizon/vehicle-dsm#1]
Hi, I'm working on vehicle speed measurement using single camera and I'm glad to follow your great work.

I got an issue when I run your code.
I put the command `./run-dsm.sh ../../dataset/set1/`. And then, the error messages are:

> Setting pipeline to PAUSED ...
> Pipeline is PREROLLING ...
> Missing element: H.264 decoder
> ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0: Your GStreamer installation is missing a plug-in.
> Additional debug info:
> gstdecodebin2.c(4640): gst_decode_bin_expose (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0:
> no suitable plugins found:
> Missing decoder: H.264 (video/x-h264, stream-format=(string)byte-stream)
> 
> ERROR: pipeline doesn't want to preroll.
> Setting pipeline to NULL ...
> Freeing pipeline ...

I tried to figure out the reason but I couldn't...
My system is Ubuntu16.04

Any help will be appreciated.

**Comment by czh55** [comment]
try this.`sudo apt-get install gstreamer1.0-plugins-bad`
see [https://askubuntu.com/questions/384650/how-to-install-h-264-decoder](url)
