### ISSUE TITLE
[Makefile:784: libvehicledsm_la-vehicle-speed.lo] Error 1

### ISSUE THREAD

**Issue by ZIKO94ZIKO** [dluvizon/vehicle-dsm#12]
![image](https://user-images.githubusercontent.com/52079137/65322161-f2b7f000-db9d-11e9-8bf0-6f01843aa42e.png)
sir when i run this commandes lines : `cd gst-plugin
  ./autogen.sh
  make
` i find this errors help me please

**Comment by dluvizon** [comment]
Please make sure you have all the required packages installed before creating an issue.
https://github.com/dluvizon/vehicle-dsm#dependencies
