### ISSUE TITLE
vehicledsm not found

### ISSUE THREAD

**Issue by RRR11** [dluvizon/vehicle-dsm#13]
The .so file is created and during inspect the it throws out a error vehicledsm not found and its not a gstreamer plugin.

-rwxr-xr-x 1 root root 2649088 Nov  6 16:06 libgstplugin.so

sudo ./inspect.sh
No such element or plugin 'vehicledsm'

Could you please let me know of the version of the gstreamer
Thanks in advance

**Comment by RRR11** [comment]
Plugin Details:
  When I inspect the plugin the following is what the system displays: can it be attributed to version mismatch
Name                     libgstplugin.so
  Description              Plugin for blacklisted file
  Filename                 ../gstreamer/.libs/libgstplugin.so
  Version                  0.0.0
  License                  BLACKLIST
  Source module            BLACKLIST
  Binary package           BLACKLIST
  Origin URL               BLACKLIST

**Comment by dluvizon** [comment]
Hi @RRR11 ,

Are you using gstreamer**1.0**?
Please note that this is a replicated issue on #6 .

**Comment by ashkanksh** [comment]
Hi I have the same issue and I spend 10 days to find a solution. Do you know what is solution? I showed the linked issue however you didn't answer there
