### ISSUE TITLE
How did you obtain ipm_left and ipm_top for calculating hmatrix ?

### ISSUE THREAD

**Issue by pawan9** [dluvizon/vehicle-dsm#14]
Hi @dluvizon 
I can see that `perspective-transform.cpp` has a method named `generate_hmatrix`, in that three variables `pixels_per_m`, `ipm_top`, `ipm_left` are used.
 I want to know how you obtained values of these variables ? Did you manually first transformed the image of camera then obtain these values from that transformed image ??

**Comment by dluvizon** [comment]
Hi, this is for the Inverse Perspective Mapping, so you can define it as you want, usually as an aligned rectangle.
But then, once you define it, you have to consider the projection the is defined.
For example, if you select points in the lane that corresponds to a square of `2x2` meters and you define your IPM values as a `200x200` pixels, than you'll have, in the inverse mapping, a scale of 1 cm / pixel.
