### ISSUE TITLE
About files lanes.xml and matrix.txt

### ISSUE THREAD

**Issue by HaiYu01** [dluvizon/vehicle-dsm#2]
Hello!
Your works are very great!
For files lanes.xml and matrix.txt,I have two questions.
1. matrix.txt is Homography matrix of 3 lines? Were they calculated according to the method in the paper(A Video-Based System for Vehicle Speed Measurement in Urban Roadways)? My  Homography matrixes are diffrent.I feel very confused.Is the speed then calibrated by a factor of 0.9?
2. In  lanes.xml ,  To whom do the  x,y coordinates belong? Which one is real world coordinates? In the paper(A Video-Based System for Vehicle Speed Measurement in Urban Roadways),you assume that the top-left corner of the rectangle(4.8m*2m) is the origin of the world coordinate system,but,I can not find it in the file  lanes.xml.
I hope you can answer my questions. It means a lot to me. thank you very much！

**Comment by dluvizon** [comment]
Hi @HaiYu01 ,

I am sorry for the long delay.

1. The file matrix.txt contains one homograph matrix per lane. Yes.
There is one coefficient per lane (in file speed.cpp) to compensate the height of the license plate with respect to the ground. Those values were estimated empirically.

2. In lanes.xml, all values correspond to pixel coordinates, in the image plane. This file does not contains the homograph transformation. It is used to define the polygon in the image corresponding to each lane, as well as the polygon corresponding to the measurement region. When a vehicle is tracked, the right transformation is selected based on these regions.

**Comment by pawan9** [comment]
Hi @dluvizon 
I have a question as to how you calculated `ref_dist_pixels`. In [`speed.cpp`](https://github.com/dluvizon/vehicle-dsm/blob/c10a60655b5864d83e65791402cc592a7e8340fb/gst-plugin/src/speed/speed.cpp#L15) i can see that you have set it to 60.0 but if i divide measurement region's height (given in lanes.xml) by 4.8 ( height of region mentioned in your paper) it is around 70.4.  So i want to know how you calculated it ?

Also in your answer above when you say 
> The file matrix.txt contains one homograph matrix per lane.
The homography matrix is for the measurement region and not for whole lane ?

**Comment by pawan9** [comment]
Hey @dluvizon in the answer above when you say 
> The file matrix.txt contains one homograph matrix per lane

the homography matrix is for measurement region and not for lane region ?

**Comment by dluvizon** [comment]
Hi @pawan9 , there is one homography matrix per lane, because the road is not flat, as can be noted from some videos.
