### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by ethanglaser** [dluvizon/vehicle-dsm#3]
![screenshot from 2019-02-27 12-16-20](https://user-images.githubusercontent.com/42726565/53509358-9d918100-3a89-11e9-8d32-af7ebc8ae7e7.png)
I am getting this error when running make. Any idea why? Thank you for your help and very nice work.

**Comment by dluvizon** [comment]
Hi @ethanglaser ,

What version of gcc are you using?
It should work with gcc 5.5 (or lower).

**Comment by ethanglaser** [comment]
Hello,

That may be the issue. I believe I am running gcc 7.3. I will try downgrading to see if that is the issue. Thank you for your help!

Ethan Glaser

________________________________

**Comment by ethanglaser** [comment]
Now make successfully runs and libgstplugin.so exists in the .libs folder, but when I run ./inspect.sh, I get the message "No such element or plugin 'vehicledsm'"
![screenshot from 2019-03-01 14-02-34](https://user-images.githubusercontent.com/42726565/53659911-b4230e00-3c2a-11e9-9b83-d0cc39516a9a.png)

**Comment by dluvizon** [comment]
What is the size of your generated file `libgstplugin.so`?
Could you check your gstreamer blacklist with `gst-inspect-1.0 -b`?

**Comment by ethanglaser** [comment]
![screenshot from 2019-03-05 23-38-31](https://user-images.githubusercontent.com/42726565/53856415-e1abe680-3f9f-11e9-8d47-a88c8e49499f.png)
It appears to be empty. Does it look like make completed correctly? Also there are 0 blacklisted files.

**Comment by dluvizon** [comment]
If autogen.sh and make do well, your file libgstplugin.so should have about 2.6M.

**Comment by LionelLeee** [comment]
my file libgstplugin.so  have about 2.6M,but when I run ./inspect.sh, I also get the message "No such element or plugin 'vehicledsm'".why is this?

**Comment by dluvizon** [comment]
If the file libgstplugin.so was correctly generated, then it should be a problem related to Gstreamer, and not necessarily to the provided code.
Unfortunately, I am not able to replicate this issue.

**Comment by ethanglaser** [comment]
No worries, thank you for trying.

Ethan Glaser

________________________________

**Comment by ZIKO94ZIKO** [comment]
please any update about this issue ,,,???

**Comment by ZIKO94ZIKO** [comment]
@ethanglaser any update

**Comment by ethanglaser** [comment]
@ZIKO94ZIKO no I haven't been working with this code for a while.

**Comment by ZIKO94ZIKO** [comment]
ok sir ,you find an other code  some of this code ?
