### ISSUE TITLE
 fatal error: opencv2/objdetect/objdetect.hpp: No such file or directory

### ISSUE THREAD

**Issue by chandu0211** [dluvizon/vehicle-dsm#4]
Hello,
 I'm trying to run the code but I'm getting the following issue while running make command.
" fatal error: opencv2/objdetect/objdetect.hpp: No such file or directory"
![Screenshot from 2019-03-26 15-36-47](https://user-images.githubusercontent.com/46132286/54990658-44adfd80-4fe1-11e9-8d5f-e2898b80a2d7.png)

I'm using GCC 5.5 version.
I have installed OpenCV and linked all the libraries also I have set the path correctly.
I tried to figure out the issue but I'm unable to figure it out.
Does Including absolute address instead of relative address will help or not?
Any help is greatly appreciated.

**Comment by dluvizon** [comment]
Hi @chandu0211 ,
If you already solved the problem, please close the issue.

**Comment by chandu0211** [comment]
The following issue has been solved by using the following commands
sudo apt-get install libopencv-dev 
and 
pkg-config --libs --cflags opencv
