### ISSUE TITLE
Makefile:745: recipe for target 'libvehicledsm_la-vehicle-speed.lo' failed

### ISSUE THREAD

**Issue by chandu0211** [dluvizon/vehicle-dsm#5]
Hello,
I tried running the project but I'm getting the following error while running "make" command.
Also i cannot find the .libs and libvehicledsm_la-vehicle-speed.lo folder in gstreamer folder.
![Screenshot from 2019-03-27 16-44-32](https://user-images.githubusercontent.com/46132286/55072905-59a69180-50b2-11e9-893a-2126751b0ea4.png)
Please help in solving the issue.
Thanks in advance.

**Comment by dluvizon** [comment]
It seems that you do not have g++ (required to build the software).

**Comment by chandu0211** [comment]
The above issue has been solved by using the following commands
sudo apt install g++-5
and
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 10
and
sudo update-alternatives --set c++ /usr/bin/g++
