### ISSUE TITLE
Error: While running inspect.sh

### ISSUE THREAD

**Issue by chandu0211** [dluvizon/vehicle-dsm#6]
Hello Sir,
    I have tried running the code. After running ./autogen.sh and make successfully I'm getting the following error " No such element or plugin 'vehicledsm' ".
I have checked for blacklisted files, there are zero blacklisted files.
![blacklist](https://user-images.githubusercontent.com/46132286/55275582-337d2d80-530e-11e9-8432-d9361f3def1a.png)
I have also checked size of libgstplugin.so it is about 2.0 MB.
Still it is throwing the following error.
![size and error](https://user-images.githubusercontent.com/46132286/55275609-97075b00-530e-11e9-8bbb-48fe401bb810.png)
Please help in solving the issue.
Thanks in advance.

**Comment by chandu0211** [comment]
Hello,
  I thought that I'm getting the following issue because I'm using different version of gstreamer plugin and different version of tools. But I'm using gstreamer 1. 0 tools.
![plugin error](https://user-images.githubusercontent.com/46132286/55453892-5b64dd80-55fb-11e9-8c25-f1a22a091123.png)
After checking that gstreamer plugin  and tools are of same version I thought I didn't set the path for GST_PLUGIN_PATH. So I have set the path for GST_PLUGIN_PATH by using the following command 
" **export GST_PLUGIN_PATH=/usr/local/lib/gstreamer-1.0/** " 
After doing all these still the error persists.

After that I have used " **gst-inspect-1.0 /usr/local/lib/gstreamer-1.0/libgstplugin.so** " command to make sure that your plugin is working and initialized properly. It is throwing the following error : **Could not load plugin file: File "/usr/local/lib/gstreamer-1.0/libgstplugin.so" is not a GStreamer plugin**

![libgstplugin is not a gstreamer plugin](https://user-images.githubusercontent.com/46132286/55454666-50f81300-55fe-11e9-8243-8e3fbb9ed431.png)
I'm unable to find out what might be the cause for the following error.
Please help in solving the issue.

**Comment by dluvizon** [comment]
Hi @chandu0211 ,
This seems to be a problem related to gstreamer.
I can provide some additional info that could help you in some way:
  - In my case, the file libsgtplugin.so has 2.6M (using a 64bit system)
  - When launching gst-inspect-1.0, you can give GST_PLUGIN_PATH= containing the path to the binaries.

**Comment by chandu0211** [comment]
Hello Sir,
  I'm getting these errors while running make. **"missing ac local-1.15 -I m4", "missing automake-1.15 --gnu" and " missing autoconf "** 
![aclocal autoconf error](https://user-images.githubusercontent.com/46132286/56467395-f94e0a00-643b-11e9-9e11-219ba5148732.png)
Initially I didn't notice the error while running make.
**But I have already installed ac local, automake, m4 and autoconf** installed with the following versions as in the image below.
![autotools version](https://user-images.githubusercontent.com/46132286/56467418-58138380-643c-11e9-8335-4fc6c2332f4a.png)
**Does the above error while running inspect.sh is because of this error while running make**. Is this error is caused by version mismatch or the path has to be specified explicitly for the autotools.
 Please help in solving the issue.
Thanks in advance.

**Comment by LionelLeee** [comment]
my file libgstplugin.so have about 2.6M,but when I run ./inspect.sh, I also get the message "No such element or plugin 'vehicledsm'".why is this?Is the plugin 'vehicledsm' 'generated on its own?
