### ISSUE TITLE
./configure && make && make install error

### ISSUE THREAD

**Issue by saiteja1995** [dluvizon/vehicle-dsm#8]
Hello,
  I'm getting the following error while running the command ./configure && make && make install.
![configure error](https://user-images.githubusercontent.com/49980731/58427669-ef17cf00-80bd-11e9-8a5c-c0647d037fdb.png)
Any help is appreciated.
Thanks in advance.

**Comment by dluvizon** [comment]
Hello,
What is the output of `./autogen.sh`?
